### ISSUE TITLE
show all button disable/enable css fixes

### ISSUE THREAD

**Issue by esmyers** [USGS-WiM/sparrow-eastern-us-js#22]

**Comment by rstevensonUSGS** [comment]
Not sure if this is where this goes.. and I am sure you are aware of it. but one of the buttons at the bottom of the application (see image below) is cut off? 
![cut_off](https://user-images.githubusercontent.com/22685263/43486331-d04d0e98-94d0-11e8-9880-3663d1fa5710.PNG)

**Comment by esmyers** [comment]
Yeah we need to fix that. I think I want to simplify our lives by not changing the button text to say "all" or "selected"  it just gets too weird
