### ISSUE TITLE
check dynamic chart button title for inconsistencies

### ISSUE THREAD

**Issue by esmyers** [USGS-WiM/sparrow-eastern-us-js#23]
1. "show Chart For Selected Features" text is not removed after leaving selection mode and viewing the chart.  Probably will want to just keep the show chart button for consistency,

2.  "select on map" section button should be relabeled from "click" to "click to select on map", "start map selection" or something more descriptive 
![image](https://user-images.githubusercontent.com/2495167/43487068-151c8a1c-94db-11e8-9169-396563d8d19e.png)

3. on load the selection button reads "click" and after selection it always reads "select"

4.  After chosing an area of interest that activates the chart button, the signal glyphicon disappears from the chart button text.

**Comment by rstevensonUSGS** [comment]
With regards to the dynamic charts that popup when you click on a specific area, why is load not capitalized with regards to the title. Total Phosphorus Accumulated load? Should the l be captialized to match the rest of the title? Total Phosphorous Accumulated Load? Just a thought.

**Comment by esmyers** [comment]
If I am seeing this correctly it appears to be the mouseover css set by the highcharts button library.
![image](https://user-images.githubusercontent.com/2495167/43486799-59bbbeaa-94da-11e8-9857-20258c763e6a.png)
