### ISSUE TITLE
Duplicate of Map Layers 

### ISSUE THREAD

**Issue by rstevensonUSGS** [USGS-WiM/sparrow-eastern-us-js#25]
The Issue starts when I click on the Map Layers and add Phosphorus or Nitrogen Calibration Sites. If I turn that layer off and then click it back on, there is a duplicate in the explanation legend. 

When I hit F5 to refresh the page, it clears everything. 

I've attached images shows the duplicates of the calibration sites. 
![duplicate_p](https://user-images.githubusercontent.com/22685263/43488639-9af1610c-94d7-11e8-8ddb-73930e4b2694.png)

This issue also happens with the Nitrogen Sites.
![duplicate_n](https://user-images.githubusercontent.com/22685263/43488855-3f6e41e6-94d8-11e8-9ad7-e8935cb95ea4.png)

Update: This happens with all the Map Layers except for Model Area and Land Use 2002. See Images 

Model:

_Sorry I just keep noticing small pieces of this issue_
![duplicate_model](https://user-images.githubusercontent.com/22685263/43490309-5f0e80ce-94dd-11e8-88da-f194c80f76b9.png)

Rivers: 
![major_rivers](https://user-images.githubusercontent.com/22685263/43489849-9637341c-94db-11e8-888d-eb85fbc68840.PNG)

Streams:
![streams_2](https://user-images.githubusercontent.com/22685263/43489872-abc36ecc-94db-11e8-832e-2f093415e57a.PNG)

![duplicate_streams](https://user-images.githubusercontent.com/22685263/43489908-d339d57c-94db-11e8-9348-3abea8720030.PNG)

**Comment by rstevensonUSGS** [comment]
To add to this, It doesn't seem to add additional points to the map, at least in that regard, it just loads one layer of the calibration sites. So there arent three layers. It just duplicates in the explanation area.

**Comment by esmyers** [comment]
next update will fix this in eastern U.S.
