### ISSUE TITLE
get Rachel access to AWS sandbox

### ISSUE THREAD

**Issue by esmyers** [USGS-WiM/sparrow-eastern-us-js#30]
Aaron, can Rachel get a user account set up for our jump server, 10.5 jumpserver, and our sparrowTest instance?  Not sure what we need to get her up and running in our AWS sandbox.  Let me know if you have any questions.

**Comment by aaronstephenson** [comment]
Both of those servers are in our WIMCLOUDAD domain, so I created a new domain account for Rachel and informed her how to use it. @esmyers you will want to show her the ropes re: how the jump server works with remote AGS servers.

**Comment by esmyers** [comment]
Thanks Aaron, can we also get her an account in our AWS sandbox so she can log into the console, add items to S3 etc?

**Comment by esmyers** [comment]
buckets:
sparrow.wim.usgs.gov
test.wim.usgs.gov
wim.usgs.gov

not sure of any others.

**Comment by aaronstephenson** [comment]
IAM user created, access to listed buckets allowed, email to Rachel sent.
