### ISSUE TITLE
Test server environment needed

### ISSUE THREAD

**Issue by esmyers** [USGS-WiM/sparrow-eastern-us-js#9]
we could go with arc 10.5 instance if possible given our Jump server is 10.4, otherwise a 10.4 would still work.  
Will need to be able to connect through AGS Jump server.

**Comment by aaronstephenson** [comment]
I'm launching two 10.5 instances, one jump server and one for SPARROW Test.

**Comment by aaronstephenson** [comment]
Done. Both the new jump server and SPARROW Test are hooked up to WIMCLOUDAD and fully licensed, and the SPARROW Test has a fully functional ArcGIS Server: https://sparrowtest.wim.usgs.gov/arcgis/rest/services/

**Comment by esmyers** [comment]
Thanks. I'm in.  Copying data now and getting down to business.
